# Methods I: Programming and Data Analysis

## Session 13: Recursion; Jupyter notebooks; NumPy

### Gerhard Jäger

#### (based on Johannes Dellert's slides)

February 1, 2022

# Recursion

A central concept of programming: **recursion**

-   informally: a definition or function which refers to itself

-   can be used whenever a problem (e.g. finding all sources of a river)
    can be reduced to subproblems of the same type (e.g. finding the sources of a tributary)

-   All loops can be implemented using recursion!

-   Every recursive function can be implemented using iteration!

-   BUT: there are many problems for which either iteration or recursion
    is more efficient, or easier to implement

### Base Case and Recursive Cases

In computing, recursive definitions need to consist of two parts:

-   the **base case** covers the simplest instances of a problem, and
    does not refer to the concept being defined (ensures termination)

-   the **recursive case** refers to the concept being defined when
    describing substructures (expansion to structures of arbitrary size)

There is a close relationship between recursion and mathematical
induction!

-   In induction, you prove that a theorem holds e.g. for $n = 1$ (the
    base case), and that it holds for $n = k + 1$ if it already holds
    for $n = k$ (recursive case).

-   If you want to prove that a recursive algorithm gives the correct
    result, you need induction as a proof technique!

### Recursive Definitions

Using recursion in definitions:

-   **recursive definition**: a definition which uses the term it
    defines

-   Example: defining (a subset of) boolean expressions in Python

    -   the expressions `True` and `False` are boolean expressions (base
        case)

    -   an expression of the form `a == b` is a boolean expression (base
        case)

    -   two boolean expressions conjoined by `and` form a boolean
        expression (recursive case)

    -   two boolean expressions conjoined by `or` form a boolean
        expression (recursive case)

    -   a boolean expression preceded by `not` is a boolean expression (recursive case)

-   you have probably seen recursive definitions in logic!

### Recursive Functions

Using recursion in function definitions:

-   **recursive function**: a function which calls itself

-   if the function calls itself on every input, we get **infinite
    recursion**

-   in all useful recursive functions, each nested call differs in its
    arguments (e.g. execution on subproblems)

-   for recursive functions to terminate, we need base cases!

### Recursion vs. Iteration

-   in principle, recursion and iteration are equally powerful\
    (one can be used to emulate the other)

-   however, there are many definitions and algorithms which are much
    easier to write using recursion

-   this is especially the case for processing data structures which
    contain substructures of varying size (i.e. data that is not tabular
    in shape)

-   Examples:

    -   processing syntax trees for programming languages (in a
        compiler) and natural languages (in a parser)

    -   processing more general graph structures like networks

    -   sorting and searching in structures that are more complex than
        lists or dictionaries (e.g. 3-D models)

-   We are going to use navigation through trees as our main example!

# Implementing Trees
---------------

### Tree Structures in Linguistics

Trees are ubiquitous in linguistics:

-   syllable structure trees

-   word structure trees

-   phrase structure trees

-   dependency trees

-   derivation trees

-   formula structure trees

### Tree Structures in Programming

Trees are one of the most important data structures in computer science:

-   the best way to maintain sorted records

-   efficient retrieval and insertion of elements

Important application areas where trees arise:

-   directory structure on a file system

-   program execution gives rise to call trees

-   software packages depend on each other in a tree shape

-   the search space of many algorithms is tree-shaped

### Modeling Nodes

Developing a simple tree class:

-   each tree node should be the instance of a class `Node`

-   the contents of a node (e.g. the category label in a syntax tree)
    should be stored as an instance variable

-   references to the children of the current node are stored in an
    additional instance variable as a list (order matters!)

-   a leaf node is modeled by empty children list

-   the result is an example of a **recursive data structure**

Actually, each `Node` corresponds to the `Tree` of which it forms the
root!

###  Modeling A Tree

In [1]:
class Tree(object):
    def __init__(self, name='root', children=None):
        self.name = name
        self.children = []
        self.parent = None
        if children is not None:
            for child in children:
                self.add_child(child)
                child.parent = self

    def add_child(self, node):
        assert isinstance(node, Tree)
        self.children.append(node)

Notes:

-   additional parent pointer makes upward navigation easier

-   the trivial `Tree` does not have children,\
    representing a single node with the label `"root"`

### Tree Traversal

Traversals are an important part of processing trees:

-   a **traversal** defines the order in which the nodes of a tree are
    processed

-   three logical possibilities:

    -   **in-order** traversal (left child first, parent, then other
        children)

    -   **pre-order** traversal (parent first, then children from left
        to right)

    -   **post-order** traversal (children from left to right, then
        parent)

-   all three variants are easiest to implement as recursive functions




### In-Order Traversal

![image.png](_img/tree1.svg)

In which order are nodes visited by an in-order traversal?

### In-Order Traversal: Solution

![image.png](_img/tree1.svg)


Solution: B, A, F, D, G, H, C, E

### In-Order Traversal: Code

Implementation within the `Tree` class:

In [2]:
def inorder(self):
    """In-order traversal:
    First recurse into left child, then visit the node itself, 
    then recurse into other children in order.
    
    :return: A list of tree nodes in in-order."""
    result = []
    if len(self.children) > 0:
        result += self.children[0].inorder()
    result.append(self)
    for i in range(1,len(self.children)):
        result += self.children[i].inorder()
    return result

### Pre-Order Traversal

![image.png](_img/tree1.svg)

In which order are nodes visited by a pre-order traversal?

### Pre-Order Traversal: Solution
![image.png](_img/tree1.svg)

Solution: A, B, C, D, F, G, H, E


### Post-Order Traversal

![image.png](_img/tree1.svg)

In which order are nodes visited by a pre-order traversal?

### Post-Order Traversal: Solution

![image.png](_img/tree1.svg)

Solution: B, F, G, H, D, E, C, A

### Jupyter notebooks

-   browser-based environment for interactive computation

-   relies on a *kernel* for the programming language you want to use

-   there are kernels for Python, R, Julia etc.



-   at the command prompt, type `jupyter notebook`

-   a browser window will open

-   select **new**, and then **Python 3**

-   the text window acts like a Python console, but you can enter
    multiple lines

-   Jupyter notebooks are great for data analysis

-   for actual programming, it is better to use Spyder or something
    similar

# The NumPy library

(see http://cs231n.github.io/python-numpy-tutorial/ and https://docs.scipy.org/doc/numpy/user/quickstart.html)

<sub>Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

## Arrays

<sub>A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(a.shape)

(3,)


In [5]:
print(a[0], a[1], a[2])   

1 2 3


In [6]:
a[0] = 5                  # Change an element of the array
print(a)                 

[5 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array# Prints "(2, 3)"


In [8]:
print(b[0, 0], b[0, 1], b[1, 0])  

1 2 4


## An example

In [9]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.dtype.name

'int64'

In [13]:
a.itemsize

8

In [14]:
a.size

15

In [15]:
type(a)

numpy.ndarray

In [16]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

## Creating arrays

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [18]:
a = np.array([2, 3, 4])
print(a)

[2 3 4]


In [19]:
a.dtype

dtype('int64')

In [20]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [21]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


The type of the array can also be explicitly specified at creation time:

In [22]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is `float64`.

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides a function analogous to `range` that returns arrays instead of lists.

In [26]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
np.arange( 0, 2, 0.3 )  

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])